//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIO.UI.Ideia {
    
    
    public partial class IdeiaVisualizacao {
        
        /// <summary>
        /// ucIdeiaExibicao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIIO.UI.Common.Controles.UcIdeiaExibicao ucIdeiaExibicao;
        
        /// <summary>
        /// ucIdeiaMarcarInteresse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIIO.UI.Ideia.IdeiaVisualizacaoControles.UcIdeiaMarcarInteresse ucIdeiaMarcarInteresse;
    }
}
