//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIO.UI {
    
    
    public partial class Default {
        
        /// <summary>
        /// UcTopo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIIO.UI.DefaultControles.UcTopo UcTopo1;
        
        /// <summary>
        /// UcPesquisa1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIIO.UI.DefaultControles.UcPesquisa UcPesquisa1;
        
        /// <summary>
        /// uciIdeiaRecentes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIIO.UI.DefaultControles.UcTop10Ideia uciIdeiaRecentes;
        
        /// <summary>
        /// uciIdeiaMaisVistos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIIO.UI.DefaultControles.UcTop10Ideia uciIdeiaMaisVistos;
        
        /// <summary>
        /// UcComoFunciona1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIIO.UI.DefaultControles.UcComoFunciona UcComoFunciona1;
        
        /// <summary>
        /// UcPublicidade1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIIO.UI.DefaultControles.UcPublicidade UcPublicidade1;
        
        /// <summary>
        /// UcRodape control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIIO.UI.DefaultControles.UcRodape UcRodape;
    }
}
